# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
